finished my part of player
vassilmladenov/cs429-WW3 pull request #11
Opened 2017-02-11 21:41 UTC by AlexWIllini

2017-02-11 21:43 UTC, shmasmasnash commented on Player.cs
> +        if (isEmpty == empty)
Just return the list even if empty

2017-02-11 21:44 UTC, shmasmasnash requested changes
Remove the null return block

2017-02-11 22:05 UTC, vassilmladenov commented
Thanks, please clean up the last of the style issues, then squash all your commits into one with an interactive rebase.

2017-02-11 22:13 UTC, AlexWIllini commented
Why would I have to squash all my commits into one if I'm just committing to my local branch? Wouldn't it just show up as a single commit when the pull request gets accepted by you for the upstream master?

2017-02-11 22:15 UTC, shmasmasnash approved these changes

2017-02-11 22:32 UTC, merged

2017-02-12 02:15 UTC, vassilmladenov commented
To answer your question, no, because that's not how rebase works. If we were only using merge commits, then yes, it would create a single commit here. What this does is it replays the commits of your feature branch onto master so that you get one continuous stream of history.